### ISSUE TITLE
Installation broken on MacOS M3

### ISSUE THREAD

**Issue by janfb** [diyabc/abcranger#100]
In a condo environment with python 3.10
```bash
pip install pyabcranger
```

results in: 
```bash
Collecting pyabcranger
  Using cached pyabcranger-0.0.70.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      PYTHON VERSION : 3.10
      running egg_info
      egg_info (cmake)
      writing dist/pyabcranger.egg-info/PKG-INFO
      writing dependency_links to dist/pyabcranger.egg-info/dependency_links.txt
      writing top-level names to dist/pyabcranger.egg-info/top_level.txt
      Cloning into 'ranger'...
      Cloning into 'wingetopt'...
      -- The CXX compiler identification is AppleClang 15.0.0.15000309
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/g++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Compiler ID : AppleClang
      -- The C compiler identification is AppleClang 15.0.0.15000309
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Found Python: /Users/janteusen/miniconda3/envs/sbibm/bin/python (found version "3.10.0") found components: Interpreter Development.Module
      -- [pmm] Using vcpkg executable: /Users/janteusen/.local/share/pmm/2.1.0/vcpkg-6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2/vcpkg
      CMake Error at build/_pmm/2.1.0/vcpkg.cmake:168 (message):
        Failed find portfile in
        /private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-install-qgxrj9oq/pyabcranger_7b698f5675f14453ba07bd871cef0b38/pybind11-nodep!
      Call Stack (most recent call first):
        build/_pmm/2.1.0/vcpkg.cmake:224 (_pmm_vcpkg_copy_custom_ports)
        build/_pmm/2.1.0/main.cmake:46 (_pmm_vcpkg)
        build/_pmm/2.1.0/main.cmake:66 (_pmm_project_fn)
        CMakeLists.txt:83 (pmm)
      
      
      -- Configuring incomplete, errors occurred!
      [git] .gitmodules found. Cloning the submodules if necessary
      [git] cloning https://github.com/fradav/ranger.git to ranger...
      [git] cloning complete.
      [git] cloning https://github.com/alex85k/wingetopt.git to wingetopt...
      [git] cloning complete.
      
      [cmake] configuring CMake project...
      
      Traceback (most recent call last):
        File "/Users/janteusen/miniconda3/envs/sbibm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/janteusen/miniconda3/envs/sbibm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/janteusen/miniconda3/envs/sbibm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/cmaketools/__init__.py", line 98, in setup
          _setup(**setup_args)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/cmaketools/cmakecommands.py", line 72, in find_sources
          mm.run()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/cmaketools/cmakecommands.py", line 452, in finalize_options
          self.cmake.configure(self.build_base, **cmake_settings)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/cmaketools/cmakebuilder.py", line 321, in configure
          cmakeutil.configure(".", build_dir, *args, **kwargs)
        File "/private/var/folders/8b/twrk9drd50l015by37329_7m0000gn/T/pip-build-env-cyhhy90a/overlay/lib/python3.10/site-packages/cmaketools/cmakeutil.py", line 120, in configure
          sp.run(args, env=env, check=True).check_returncode()
        File "/Users/janteusen/miniconda3/envs/sbibm/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '.', '-B', 'build', '-DPython_EXECUTABLE=/Users/janteusen/miniconda3/envs/sbibm/bin/python', '-DPYABCRANGER=TRUE', '-DUSE_MKL:BOOL=FALSE', '-DCMAKE_BUILD_TYPE:STRING=Release', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE:STRING=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

seems to be reproducible on different machines, see https://github.com/sbi-benchmark/sbibm/issues/66#issuecomment-2032934854

**Comment by sdemita** [comment]
Yes I also get these same error (pmm not finding pybind11-nodep portfile) on my Fedora 39, Python 3.12, pip 23.2.

See also issue #96.

Details:

```
Using pip 23.2.1 from /usr/lib/python3.12/site-packages/pip (python 3.12)
Defaulting to user installation because normal site-packages is not writeable
Collecting pyabcranger
  Using cached pyabcranger-0.0.70.tar.gz (58 kB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/f7/29/13965af254e3373bceae8fb9a0e6ea0d0e571171b80d6646932131d6439b/setuptools-69.5.1-py3-none-any.whl.metadata
    Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl.metadata
    Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
  Collecting cmaketools
    Obtaining dependency information for cmaketools from https://files.pythonhosted.org/packages/97/1d/3a98e75fb84a2e53a0b119ad832234fdc28b88c0adb923e7c7527f6ba370/cmaketools-0.1.6-py3-none-any.whl.metadata
    Using cached cmaketools-0.1.6-py3-none-any.whl.metadata (16 kB)
  Collecting cmake>=3.18
    Obtaining dependency information for cmake>=3.18 from https://files.pythonhosted.org/packages/be/2e/8f8daa34e6d743816f852c752da544c34ead6b4fbbdf547519430bdba590/cmake-3.29.2-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
    Using cached cmake-3.29.2-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.1 kB)
  Collecting ninja
    Obtaining dependency information for ninja from https://files.pythonhosted.org/packages/6d/92/8d7aebd4430ab5ff65df2bfee6d5745f95c004284db2d8ca76dcbfd9de47/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata
    Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
  Collecting vswhere
    Using cached vswhere-1.4.0-py3-none-any.whl
  Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
  Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
  Using cached cmaketools-0.1.6-py3-none-any.whl (23 kB)
  Using cached cmake-3.29.2-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
  Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
  Installing collected packages: vswhere, ninja, cmaketools, wheel, setuptools, cmake
  Successfully installed cmake-3.29.2 cmaketools-0.1.6 ninja-1.11.1.1 setuptools-69.5.1 vswhere-1.4.0 wheel-0.43.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  PYTHON VERSION : 3.12
  running egg_info
  egg_info (cmake)
  writing dist/pyabcranger.egg-info/PKG-INFO
  writing dependency_links to dist/pyabcranger.egg-info/dependency_links.txt
  writing top-level names to dist/pyabcranger.egg-info/top_level.txt
  Cloning into 'ranger'...
  Cloning into 'wingetopt'...
  -- The CXX compiler identification is GNU 13.2.1
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  Compiler ID : GNU
  -- The C compiler identification is GNU 13.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/lib64/ccache/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Found BLAS: -Wl,--start-group /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.a /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_tbb_thread.a /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.a -Wl,--end-group;pthread;m;dl
  -- Found LAPACK: -Wl,--start-group /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_lp64.a /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_tbb_thread.a /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.a -Wl,--end-group;pthread;m;dl
  -- Found Python: /usr/bin/python3 (found version "3.12.2") found components: Interpreter Development.Module
  -- [pmm] Using vcpkg executable: /home/stephane/.local/share/pmm/2.1.0/vcpkg-6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2/vcpkg
  CMake Error at build/_pmm/2.1.0/vcpkg.cmake:168 (message):
    Failed find portfile in
    /tmp/pip-install-2fkm52yt/pyabcranger_4da10669677545e8a28d9fd1b3778f79/pybind11-nodep!
  Call Stack (most recent call first):
    build/_pmm/2.1.0/vcpkg.cmake:224 (_pmm_vcpkg_copy_custom_ports)
    build/_pmm/2.1.0/main.cmake:46 (_pmm_vcpkg)
    build/_pmm/2.1.0/main.cmake:66 (_pmm_project_fn)
    CMakeLists.txt:83 (pmm)


  -- Configuring incomplete, errors occurred!
```

**Comment by fradav** [comment]
related to #101 closing
