### ISSUE TITLE
Pip install error on Macbook:  'ModuleNotFoundError: No module named 'cmaketools'

### ISSUE THREAD

**Issue by JeremySMorgan** [diyabc/abcranger#68]
Version 0.0.24. Command: `python -m pip install pyabcranger` results in the following error:
```
Collecting pyabcranger
  Using cached pyabcranger-0.0.24.tar.gz (50 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-pnuapdlb/pyabcranger/setup.py'"'"'; __file__='"'"'/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-pnuapdlb/pyabcranger/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-da_68b74
         cwd: /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-pnuapdlb/pyabcranger/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-pnuapdlb/pyabcranger/setup.py", line 1, in <module>
        from cmaketools import setup
    ModuleNotFoundError: No module named 'cmaketools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Is there someway to fix this issue? Are there any dependencies I need?  

Thanks

**Comment by JeremySMorgan** [comment]
Just realized I needed to install `cmake` and `cmaketools` (`python -m pip install cmake cmaketools`)
