### ISSUE TITLE
Error installing with pip: ` ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

### ISSUE THREAD

**Issue by JeremySMorgan** [diyabc/abcranger#69]
I'm trying to install version 0.0.24, my commands:

`python -m pip install cmake cmaketools`
`python -m pip install pyabcranger`

Error message:
```
 ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-v7ljvepq/pyabcranger/setup.py'"'"'; __file__='"'"'/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-v7ljvepq/pyabcranger/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-s5f0hpig
         cwd: /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-v7ljvepq/pyabcranger/
    Complete output (380 lines):
    running egg_info
    egg_info (cmake)
    creating /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-s5f0hpig/pyabcranger.egg-info
    writing /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-s5f0hpig/pyabcranger.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-s5f0hpig/pyabcranger.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-s5f0hpig/pyabcranger.egg-info/top_level.txt
    writing manifest file '/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-pip-egg-info-s5f0hpig/pyabcranger.egg-info/SOURCES.txt'
    Cloning into 'ranger'...
    Cloning into 'wingetopt'...
    Not searching for unused variables given on the command line.
    -- The CXX compiler identification is AppleClang 10.0.1.10010046
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    Compiler ID : AppleClang
    -- The C compiler identification is AppleClang 10.0.1.10010046
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- [pmm] Failed to check for updates (Couldn't download https://raw.githubusercontent.com/fradav/pmm/latest-info.cmake)
    -- [pmm] Downloading vcpkg at 6185aa76504a5025f36754324abf307cc776f3da ...
    -- [download 100% complete]
    -- [pmm] Extracting vcpkg archive...
    -- [pmm] Bootstrapping the vcpkg tool (This may take a minute)...
    CMake Error at build/_pmm/1.5.11/vcpkg.cmake:72 (message):
      Failed to Bootstrap the vcpkg tool [1]:
    
      -- The CXX compiler identification is AppleClang 10.0.1.10010046
    
      -- Detecting CXX compiler ABI info
    
      -- Detecting CXX compiler ABI info - done
    
      -- Check for working CXX compiler:
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      - skipped
    
      -- Detecting CXX compile features
    
      -- Detecting CXX compile features - done
    
      -- Detecting the C++ standard library
    
      -- Detecting the C++ standard library - libc++
    
      -- Detecting how to use the C++ filesystem library
    
      -- Detecting how to use the C++ filesystem library - <filesystem>
    
      -- Looking for C++ include pthread.h
    
      -- Looking for C++ include pthread.h - found
    
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    
      -- Found Threads: TRUE
    
      -- Configuring done
    
      -- Generating done
    
      -- Build files have been written to:
      /Users/admin/.local/share/pmm/1.5.11/vcpkg-tmp/vcpkg-6185aa76504a5025f36754324abf307cc776f3da/toolsrc/build.rel
    
    
      [0/2] Re-checking globbed directories...
    
      [1/77] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o
    
      FAILED: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -MF
      CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o.d -o
      CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -c ../src/vcpkg.cpp
    
      In file included from ../src/vcpkg.cpp:6:
    
      ../include/vcpkg/base/files.h:7:10: fatal error: 'filesystem' file not
      found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [2/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o -c
      ../src/vcpkg/base/checks.cpp
    
      In file included from ../src/vcpkg/base/checks.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [3/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o -c
      ../src/vcpkg/base/chrono.cpp
    
      In file included from ../src/vcpkg/base/chrono.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [4/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/enums.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/enums.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/enums.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/enums.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/enums.cpp.o -c
      ../src/vcpkg/base/enums.cpp
    
      In file included from ../src/vcpkg/base/enums.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [5/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o
      -MF CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o -c
      ../src/vcpkg/base/downloads.cpp
    
      In file included from ../src/vcpkg/base/downloads.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [6/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o -c
      ../src/vcpkg/base/cofffilereader.cpp
    
      In file included from ../src/vcpkg/base/cofffilereader.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [7/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o -c
      ../src/vcpkg/base/hash.cpp
    
      In file included from ../src/vcpkg/base/hash.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [8/77] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/archives.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/archives.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/archives.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/archives.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/archives.cpp.o -c
      ../src/vcpkg/archives.cpp
    
      In file included from ../src/vcpkg/archives.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [9/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o -c
      ../src/vcpkg/base/files.cpp
    
      In file included from ../src/vcpkg/base/files.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      [10/77] Building CXX object
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/json.cpp.o
    
      FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/json.cpp.o
    
    
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
      -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3
      -DNDEBUG -isysroot
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
      -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/json.cpp.o -MF
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/json.cpp.o.d -o
      CMakeFiles/vcpkglib.dir/src/vcpkg/base/json.cpp.o -c
      ../src/vcpkg/base/json.cpp
    
      In file included from ../src/vcpkg/base/json.cpp:1:
    
      ../include/pch.h:27:10: fatal error: 'filesystem' file not found
    
      #include <filesystem>
    
               ^~~~~~~~~~~~
    
      1 error generated.
    
      ninja: build stopped: subcommand failed.
    
    Call Stack (most recent call first):
      build/_pmm/1.5.11/vcpkg.cmake:198 (_pmm_ensure_vcpkg)
      build/_pmm/1.5.11/main.cmake:38 (_pmm_vcpkg)
      build/_pmm/1.5.11/main.cmake:52 (_pmm_project_fn)
      CMakeLists.txt:82 (pmm)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-v7ljvepq/pyabcranger/build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mc/_mk9c12121lb28mz68vfmdvw0000gr/T/pip-install-v7ljvepq/pyabcranger/setup.py", line 28, in <module>
        build_opts=["--target","pyabcranger"]
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cmaketools/__init__.py", line 98, in setup
        _setup(**setup_args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in run
        self.find_sources()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cmaketools/cmakecommands.py", line 72, in find_sources
        mm.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 531, in run
        self.add_defaults()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 567, in add_defaults
        sdist.add_defaults(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_ext()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 117, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cmaketools/cmakecommands.py", line 452, in finalize_options
        self.cmake.configure(self.build_base, **cmake_settings)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cmaketools/cmakebuilder.py", line 321, in configure
        cmakeutil.configure(".", build_dir, *args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cmaketools/cmakeutil.py", line 120, in configure
        sp.run(args, env=env, check=True).check_returncode()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['cmake', '.', '-B', 'build', '--no-warn-unused-cli -DMAKE_STATIC_EXE:BOOL=TRUE -DUSE_MKL:BOOL=TRUE -DLAPACK_ROOT:STRING=/opt/intel/mkl/lib/intel64 "-DLAPACK_LIBRARIES:STRING=-Wl,--start-group /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.a /opt/intel/mkl/lib/intel64/libmkl_tbb_thread.a /opt/intel/mkl/lib/intel64/libmkl_core.a -Wl,--end-group\\;pthread\\;m\\;dl" "-DBLAS_LIBRARIES:STRING=-Wl,--start-group /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.a /opt/intel/mkl/lib/intel64/libmkl_tbb_thread.a /opt/intel/mkl/lib/intel64/libmkl_core.a -Wl,--end-group\\;pthread\\;m\\;dl" -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja ../', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE:STRING=Release']' returned non-zero exit status 1.
    [git] .gitmodules found. Cloning the submodules if necessary
    [git] cloning https://github.com/fradav/ranger.git to ranger...
    [git] cloning complete.
    [git] cloning https://github.com/alex85k/wingetopt.git to wingetopt...
    [git] cloning complete.
    
    [cmake] configuring CMake project...
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Is there anything I can do to fix this issue? 

Thanks

**Comment by fradav** [comment]
I'm guessing you're on MacOS. The vcpkg build doesn't like apple clang version inferior to 11. I recommend installing gcc 10 and forcing into CC=gcc and CXX=g++. Have you got homebrew on your system ? it is as simple than "brew install gcc" to get it.

Besides, If you have a little patience I've planned to upload a binary release on PyPI in the coming weeks.

**Comment by fradav** [comment]
Could you retry a pip install ? Proper macos binary wheel has been pushed on Pypi.

**Comment by fradav** [comment]
Please note that due to an ongoing issue there is no binary wheel for python 3.8 on macos.

**Comment by fradav** [comment]
Latest pypi release contains all 3.6, 3.7, 3.8 wheels for macos. Feel free to reopen this issue if you got any problem.

**Comment by b4be1** [comment]
@fradav, thanks a lot for releasing the wheels for macos. Are you planning to add 3.9 too? If not, can you tell me how to build it or where I can look it up?

**Comment by fradav** [comment]
Next week maybe. I'm sorting a few things left for multi target support (see #74 ). Multi target support will bring abcranger to parity feature with abcrf: it is a boon for testing a lot of stuff in one smooth and fast pass.

I'll also add a real "pythonic" way of passing arguments to function (fix #46)
Stay tuned!

**Comment by b4be1** [comment]
Nice! Many thanks for the quick reply

**Comment by fradav** [comment]
FYI latest pypy wheels for python are out (release 0.49)
Multi target support is there too, but not the new options passing.

**Comment by b4be1** [comment]
Thanks @fradav. I currently downgraded to Python 3.8, but I will check it out on Python 3.9 in the next project.
