### ISSUE TITLE
Installation broken with python 3.10.4

### ISSUE THREAD

**Issue by psteinb** [diyabc/abcranger#92]
Hi,

inside a clean python `3.10.4` virtualenv, `pyabcranger` cannot be installed:

Error:

```bash
$ python -m pip install pyabcranger      
Requirement already satisfied: pip in ./venv-py310/lib/python3.10/site-packages (22.1)
Collecting install
  Downloading install-1.3.5-py3-none-any.whl (3.2 kB)
Collecting pyabcranger
  Using cached pyabcranger-0.0.52.tar.gz (51 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_6s7wfo_/pyabcranger_de98658d19df4f149102216f067854c6/setup.py", line 1, in <module>
          from cmaketools import setup
      ModuleNotFoundError: No module named 'cmaketools'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

My python:

```sh
$ python --version                             
Python 3.10.4
```

Steps to reproduce:
```bash
python -m venv venv-py310
source venv-py310/bin/activate
python -m pip install -U pip
```
After this, you can run the failing
```bash
python -m pip install pyabcranger      
```

**Comment by psteinb** [comment]
After tinkering around, I saw that the `cmaketools` and `wheels` packages are missing from the `setup.py`. it maybe a good idea to add the following lines to `setup.py`:
```python
# setup.py
REQUIRED = ["cmaketools", "wheels"]
# ...
setup(
		 #...
		 install_requires=REQUIRED,
)
```

But even with these additional installs, the `cmake` build fails with:
```
     -- [pmm] To update, simply change the value of PMM_VERSION_INIT in pmm.cmake
      -- [pmm] You can disable these messages by setting PMM_IGNORE_NEW_VERSION to TRUE before including pmm.cmake
      -- [pmm] NOTE: pmm.cmake has changed! Please download a new pmm.cmake from the PMM repository.
      -- Found BLAS: -Wl,--start-group /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.a /opt/intel/mkl/lib/intel64/libmkl_tbb_thread.a /opt/intel/mkl/lib/intel64/libmkl_core.a -Wl,--end-group;pthread;m;dl
      -- Found LAPACK: -Wl,--start-group /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.a /opt/intel/mkl/lib/intel64/libmkl_tbb_thread.a /opt/intel/mkl/lib/intel64/libmkl_core.a -Wl,--end-group;pthread;m;dl
      -- [pmm] Using vcpkg executable: /home/steinb95/.local/share/pmm/1.5.1/vcpkg-35c98ef06265660f036a3156d7615c735a10087c/vcpkg
      CMake Error at build/_pmm/1.5.1/vcpkg.cmake:154 (message):
        Failed find portfile in
        /tmp/pip-install-uidn27uv/pyabcranger_f10b26815e1b4019a78633a9054dfee0/pybind11-nodep!
      Call Stack (most recent call first):
        build/_pmm/1.5.1/vcpkg.cmake:202 (_pmm_vcpkg_copy_custom_ports)
        build/_pmm/1.5.1/main.cmake:38 (_pmm_vcpkg)
        build/_pmm/1.5.1/main.cmake:52 (_pmm_project_fn)
        CMakeLists.txt:86 (pmm)
```

**Comment by psteinb** [comment]
python 3.9 works like a charm as the wheels are available on pypi apparently.
